version: "3.9"

services:
  web:
    build: .
    container_name: portfolio_web
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=portfolio_mysql    
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=portfolio
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    container_name: portfolio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
